/** Declaration file generated by dts-gen */

declare module "dotenv" {
  export function config(options: any): any;

  export function load(options: any): any;

  export function parse(src: any): any;
}
