/** Declaration file generated by dts-gen */

declare module 'twitter' {

  interface TwitterOption {
    consumer_key?: string;
    consumer_secret?: string;
    access_token_key?: string;
    access_token_secret?: string;
    bearer_token?: string;
    rest_base?: string;
    stream_base?: string;
    user_stream_base?: string;
    site_stream_base?: string;
    media_base?: string;
    request_options?: {
      headers?: {
        Accept?: string;
        Connection?: string;
        'User-Agent'?: string;
        Authorization?: string;
      }
    }
  }

  type TwitterRequestParam = object;

  type TwitterRequestError = Error | null;

  type TwitterRequestCallback = (error: TwitterRequestError, data: object, response: TwitterResponse) => void;

  type TwitterResponse = {
    statusCode: number;
    statusMessage: string;
  }

  interface Twitter {
    (options: TwitterOption): Twitter;

    VERSION: any;
    allow_promise: boolean;

    get(url: string, params: TwitterRequestParam, callback: TwitterRequestCallback): void;
    get(url: string, params: TwitterRequestParam): Promise<object>;

    post(url: string, params: TwitterRequestParam, callback: TwitterRequestCallback): void;
    post(url: string, params: TwitterRequestParam): Promise<object>;

    stream(method: any, params: any, callback: any): any;
  }

  class Twitter {
    constructor(options: TwitterOption);
  }

  export = Twitter;
}
